# -*- coding: utf-8 -*-
"""Healthcare_Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JHDZQBau0-SD_VyIQVCncg_V71vSR91q
"""

import pandas as pd
import numpy as np

data = {
    'patient_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 101, 107, 118, 119, 120],
    'age': ['25', '34', None, '45', '29', None, '38', '52', '27', '41',
            '33', 'unknown', '48', '26', '35', '25', '38', '31', None, '44'],
    'weight': ['70', '65', '80', None, '75', None, '68', '90', '72', '85',
               '78', None, '82', '69', 'N/A', '70', '68', '74', None, '88'],
    'blood_pressure': [120, 130, None, 140, 125, None, 135, None, 118, 145,
                      128, None, 138, 122, None, 120, 135, 126, None, 142],
    'medication': ['Aspirin', 'Metformin', 'Lisinopril', None, 'Aspirin',
                   'Metformin', 'Lisinopril', 'Aspirin', None, 'Metformin',
                   'Lisinopril', 'Aspirin', None, 'Metformin', 'Aspirin',
                   'Aspirin', 'Lisinopril', 'Metformin', 'Aspirin', None],
    'insurance_provider': ['Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None,
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', 'Blue Cross',
                          'Aetna', None, 'UnitedHealth', 'Blue Cross', 'Aetna',
                          'Blue Cross', 'Aetna', 'Cigna', 'UnitedHealth', None]
}

df = pd.DataFrame(data)

#Task 1: Inspect the Data
# Data info
print(df.info())

# Missing values count
print(df.isnull().sum())

# Percentage of missing values
print((df.isnull().sum() / len(df)) * 100)

# Duplicate rows
print("Duplicate rows:", df.duplicated().sum())

#Task 2: Data Type Conversion
# Convert age to numeric
df['age'] = pd.to_numeric(df['age'], errors='coerce')

# Convert weight to numeric
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')

# Check new missing values after conversion
print("Missing after conversion:")
print(df[['age','weight']].isnull().sum())

# Convert insurance_provider to category
df['insurance_provider'] = df['insurance_provider'].astype('category')

# Verify data types
print(df.dtypes)

#Task 3: Handle Missing Values
# Fill numeric columns with median
df['age'].fillna(df['age'].median())
df['weight'].fillna(df['weight'].median())
df['blood_pressure'].fillna(df['blood_pressure'].median())

# Fill medication with mode
df['medication'].fillna(df['medication'].mode()[0])

# Fill insurance provider with constant
df['insurance_provider'] = df['insurance_provider'].astype('object')
df['insurance_provider'].fillna('Unknown')

# Verify no missing values remain
print(df.isnull().sum())

# Task 4: Handle Duplicates
# View duplicate rows
print(df[df.duplicated(keep=False)])

# Identify duplicates by patient_id
print(df[df.duplicated(subset=['patient_id'])])

# Shape before removing duplicates
print("Shape before:", df.shape)

# Remove duplicates
df = df.drop_duplicates(subset=['patient_id'], keep='first')

# Shape after removing duplicates
print("Shape after:", df.shape)

# Task 5: Complete Workflow with Verification
# Reload dataset
df = pd.DataFrame(data)

# Copy dataframe
df_clean = df.copy()

# Report before cleaning
print("Shape before:", df_clean.shape)
print("Missing before:\n", df_clean.isnull().sum())
print("Duplicates before:", df_clean.duplicated().sum())
print("Data types before:\n", df_clean.dtypes)

# Convert data types
df_clean['age'] = pd.to_numeric(df_clean['age'], errors='coerce')
df_clean['weight'] = pd.to_numeric(df_clean['weight'], errors='coerce')
df_clean['insurance_provider'] = df_clean['insurance_provider'].astype('category')

# Handle missing values
df_clean['age'].fillna(df_clean['age'].median())
df_clean['weight'].fillna(df_clean['weight'].median())
df_clean['blood_pressure'].fillna(df_clean['blood_pressure'].median())
df_clean['medication'].fillna(df_clean['medication'].mode()[0])
df_clean['insurance_provider'] = df_clean['insurance_provider'].astype('object')
df_clean['insurance_provider'].fillna('Unknown')

# Handle duplicates
duplicates_before = df_clean.duplicated(subset=['patient_id']).sum()
df_clean = df_clean.drop_duplicates(subset=['patient_id'], keep='first')
duplicates_after = df_clean.duplicated(subset=['patient_id']).sum()

# Final report
print("\n--- CLEANING REPORT ---")
print("Shape after:", df_clean.shape)
print("Missing after:\n", df_clean.isnull().sum())
print("Duplicates before:", duplicates_before)
print("Duplicates after:", duplicates_after)
print("Data types after:\n", df_clean.dtypes)